version: "3.9"

services:
  gpt5:
    image: selfimproving/python-dev:3.11
    working_dir: /workspace
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["bash", "-lc", "tail -f /dev/null"]
    environment:
      - HOME=/home/dev
      - SMOL_PODCASTER_DIR=/home/dev/src/smol-podcaster
      - RUNS_DIR=/workspace/runs
      - RUN_NAME=${RUN_NAME:-dev}
      - ARTIFACTS_DIR=/artifacts
      - RUN_PATH=/artifacts
    volumes:
      - ./gpt5:/workspace
      - ${HOME}/.cache/pip:/home/dev/.cache/pip
      - ${ARTIFACTS_HOST:-./gpt5/runs/dev}:/artifacts

  opus4cc:
    image: selfimproving/python-dev:3.11
    working_dir: /workspace
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["bash", "-lc", "tail -f /dev/null"]
    environment:
      - HOME=/home/dev
      - SMOL_PODCASTER_DIR=/home/dev/src/smol-podcaster
      - RUNS_DIR=/workspace/runs
      - RUN_NAME=${RUN_NAME:-dev}
      - ARTIFACTS_DIR=/artifacts
      - RUN_PATH=/artifacts
    volumes:
      - ./opus4-cc:/workspace
      - ${HOME}/.cache/pip:/home/dev/.cache/pip
      - ${ARTIFACTS_HOST:-./opus4-cc/runs/dev}:/artifacts
